// Date: 13/05/2020 10:13:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.divin.models.block;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCactalyseurDePuissance extends ModelBase
{
  //fields
    ModelRenderer Boule1;
    ModelRenderer Boule2;
    ModelRenderer Boule3;
    ModelRenderer Boule4;
    ModelRenderer sphere1;
    ModelRenderer sphere2;
    ModelRenderer sphere3;
    ModelRenderer sphere4;
    ModelRenderer sphere5;
  
  public ModelCactalyseurDePuissance()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Boule1 = new ModelRenderer(this, 0, 0);
      Boule1.addBox(-3F, -3F, -3F, 6, 6, 6);
      Boule1.setRotationPoint(0F, 17F, 0F);
      Boule1.setTextureSize(64, 32);
      Boule1.mirror = true;
      setRotation(Boule1, 0F, 0F, 0F);
      Boule2 = new ModelRenderer(this, 0, 0);
      Boule2.addBox(-3F, -3F, -3F, 6, 6, 6);
      Boule2.setRotationPoint(0F, 17F, 0F);
      Boule2.setTextureSize(64, 32);
      Boule2.mirror = true;
      setRotation(Boule2, 0.7853982F, 0F, 0F);
      Boule3 = new ModelRenderer(this, 0, 0);
      Boule3.addBox(-3F, -3F, -3F, 6, 6, 6);
      Boule3.setRotationPoint(0F, 17F, 0F);
      Boule3.setTextureSize(64, 32);
      Boule3.mirror = true;
      setRotation(Boule3, 0F, 0.7853982F, 0F);
      Boule4 = new ModelRenderer(this, 0, 0);
      Boule4.addBox(-3F, -3F, -3F, 6, 6, 6);
      Boule4.setRotationPoint(0F, 17F, 0F);
      Boule4.setTextureSize(64, 32);
      Boule4.mirror = true;
      setRotation(Boule4, 0F, 0F, 0.7853982F);
      sphere1 = new ModelRenderer(this, 0, 0);
      sphere1.addBox(8F, -6F, -8F, 1, 1, 1);
      sphere1.setRotationPoint(0F, 17F, 0F);
      sphere1.setTextureSize(64, 32);
      sphere1.mirror = true;
      setRotation(sphere1, 0F, 0F, 0F);
      sphere2 = new ModelRenderer(this, 0, 0);
      sphere2.addBox(-11F, -14F, -4F, 1, 1, 1);
      sphere2.setRotationPoint(0F, 17F, 0F);
      sphere2.setTextureSize(64, 32);
      sphere2.mirror = true;
      setRotation(sphere2, 0F, 0F, 0F);
      sphere3 = new ModelRenderer(this, 0, 0);
      sphere3.addBox(-13F, 0F, 0F, 1, 1, 1);
      sphere3.setRotationPoint(0F, 17F, 0F);
      sphere3.setTextureSize(64, 32);
      sphere3.mirror = true;
      setRotation(sphere3, 0F, 0F, 0F);
      sphere4 = new ModelRenderer(this, 0, 0);
      sphere4.addBox(-12F, -6F, 14F, 1, 1, 1);
      sphere4.setRotationPoint(0F, 17F, 0F);
      sphere4.setTextureSize(64, 32);
      sphere4.mirror = true;
      setRotation(sphere4, 0F, 0F, 0F);
      sphere5 = new ModelRenderer(this, 0, 0);
      sphere5.addBox(11F, -10F, 7F, 1, 1, 1);
      sphere5.setRotationPoint(0F, 17F, 0F);
      sphere5.setTextureSize(64, 32);
      sphere5.mirror = true;
      setRotation(sphere5, 0F, 0F, 0F);
  }
  
  public void renderAll()
  {
    Boule1.render(0.0625F);
    Boule2.render(0.0625F);
    Boule3.render(0.0625F);
    Boule4.render(0.0625F);
    sphere1.render(0.0625F);
    sphere2.render(0.0625F);
    sphere3.render(0.0625F);
    sphere4.render(0.0625F);
    sphere5.render(0.0625F);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

}
